### ISSUE TITLE
Any fvtt command throws "SyntaxError: Unexpected token '?' at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)"

### ISSUE THREAD

**Issue by PeterJamesLawson** [foundryvtt/foundryvtt-cli#29]
I am just getting started with foundryvtt (and loving it).
I was very excited to find this CLI, so I installed the latest version today.

Install appeared to be successful, but ANY command results in the same error.

OS: Ubuntu 22.04.2 LTS

<pre><font color="#26A269"><b>username@ubuntu-laptop</b></font>:<font color="#12488B"><b>~</b></font>$ sudo npm install -g @foundryvtt/foundryvtt-cli

changed 62 packages, and audited 63 packages in 6s

21 packages are looking for funding
  run `npm fund` for details

found <font color="#26A269"><b>0</b></font> vulnerabilities
<font color="#26A269"><b>username@ubuntu-laptop</b></font>:<font color="#12488B"><b>~</b></font>$ fvtt --version
file:///usr/local/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:140
            const pkg = game.worlds.get(currentPackageId) ?? game.systems.get(currentPackageId) ?? game.modules.get(currentPackageId);
                                                           ^

SyntaxError: Unexpected token &apos;?&apos;
<font color="#5E5C64">    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)</font>
</pre>

**Comment by PeterJamesLawson** [comment]
I just needed to update Node.js. Thanks for the tip on the discord server @mkahvi.
