### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by tafk7** [foundryvtt/foundryvtt-cli#44]
Having this issue attempting to put my compendium back together. Any suggestions? I haven't changed anything about the compendium since it was working, just setup a new machine.

```
rellek@Weave:~$ fvtt package pack battlemaps-purpose --in ~/cache --out ~/outdoot/
fvtt package [action] [value]

Manage packages

Positionals:
  action  The action to perform
                         [string] [choices: "workon", "clear", "unpack", "pack"]
  value   The value to use for the action                               [string]

Options:
      --version                 Show version number                    [boolean]
  -h, --help                    Show help                              [boolean]
      --id                      The package ID                          [string]
      --type                    The package type
                                 [string] [choices: "Module", "System", "World"]
  -n, --compendiumName          The Compendium name, for Compendium Pack based A
                                ctions.                                 [string]
  -t, --compendiumType          The type of document that the compendium pack st
                                ores. Only necessary for NeDB operations.
  [string] [choices: "Actor", "Adventure", "Cards", "ChatMessage", "Combat", "Fo
  gExploration", "Folder", "Item", "JournalEntry", "Macro", "Playlist", "RollTab
                                                le", "Scene", "Setting", "User"]
      --inputDirectory, --in    The directory to read from, for Pack based Actio
                                ns.                                     [string]
      --outputDirectory, --out  The directory to write to, for Pack based Action
                                s.                                      [string]
      --yaml                    Whether to use YAML instead of JSON for serializ
                                ation.                                 [boolean]
  -v, --verbose                 Whether to output verbose logging.     [boolean]
      --nedb                    Whether to use NeDB instead of ClassicLevel for
                                database operations.                   [boolean]
      --recursive               When packing, recurse down through all directori
                                es in the input directory to find source files.
                                                                       [boolean]

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at determinePaths (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:286:41)
    at handlePack (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:407:28)
    at Object.handler (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:131:28)
    at file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:128:20)
    at [runYargsParserAndExecuteCommands] (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/yargs-factory.js:1386:105)
    at YargsInstance.parse (file:///home/rellek/.nvm/versions/node/v20.8.0/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/yargs-factory.js:707:63)
```

**Comment by Fyorl** [comment]
Did you run `fvtt package workon` first?
