### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by deurk** [foundryvtt/foundryvtt-cli#45]
Hello, while trying to pack an `Actors` compendium, I run into the following error:
```
[classic-level] Packing "/home/runner/work/bleh/data/Data/modules/bleh/packs/fr-archetypes/_source" into "/home/runner/work/bleh/data/Data/modules/bleh/packs/fr-archetypes"
Failed to pack /home/runner/work/bleh/data/Data/modules/bleh/packs/fr-archetypes/_source/adepte-KqOVU0BNoNGegAgR.json. See error below.
TypeError: Cannot read properties of undefined (reading 'split')
    at compileClassicLevel (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/lib/package.mjs:282:39)
    at compilePack (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/lib/package.mjs:188:10)
    at handlePack (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:433:11)
    at Object.handler (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/commands/package.mjs:139:28)
    at file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/command.js:128:20)
    at [runYargsParserAndExecuteCommands] (file:///opt/hostedtoolcache/node/21.2.0/x64/lib/node_modules/@foundryvtt/foundryvtt-cli/node_modules/yargs/build/lib/yargs-factory.js:1386:105)
```

Does the tool support actors? I have had no issues with my items compendiums. Thanks!

**Comment by deurk** [comment]
Anything I can provide to help solve the issue?

**Comment by deurk** [comment]
My mistake, it was missing a `_key`.
